
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import querys.*;

/**
 *
 * @author ascen
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_us = new javax.swing.JTextField();
        jPasswordField_pas = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_op = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_us.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jTextField_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 330, 40));

        jPasswordField_pas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jPasswordField_pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 330, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jButton_op.setText("Entrar");
        jButton_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_opActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Punto de venta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_opActionPerformed

        // Obtener los valores de los campos de texto
        String usuario = jTextField_us.getText();
        String contraseña = new String(jPasswordField_pas.getPassword());

        // Llamar al método autenticar
        boolean autenticado = login.autenticar(usuario, contraseña);

        // Mostrar el resultado al usuario
        if (autenticado) {
            JOptionPane.showMessageDialog(this, "¡Autenticación exitosa!");

            this.dispose();
            Inicio inicio = new Inicio();
            inicio.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton_opActionPerformed

    /**
     * @param args the command line arguments
     */


        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {

            try {
                // Aplicar FlatLaf (elige entre claro o oscuro)
                UIManager.setLookAndFeel(new FlatMacLightLaf()); // Cambia si usas FlatMacLightLaf
                // UIManager.setLookAndFeel(new FlatDarkLaf()); // Tema oscuro
            } catch (Exception e) {
                System.out.println("Error al aplicar el tema: " + e.getMessage());
            }

            // Lanzar la interfaz gráfica
            javax.swing.SwingUtilities.invokeLater(() -> {
                new Login().setVisible(true); // Reemplaza con tu JFrame principal
            });
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_op;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_pas;
    private javax.swing.JTextField jTextField_us;
    // End of variables declaration//GEN-END:variables
}
